# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  external_labels:
      monitor: 'codelab-monitor'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'natsexporter1'
    metrics_path: '/metrics'
    honor_labels: true
    static_configs:
      - targets: ['nats-exporter1:7777']
 
  - job_name: 'natsexporter2'
    metrics_path: '/metrics'
    honor_labels: true
    static_configs:
      - targets: ['nats-exporter2:7777']

  - job_name: 'natsexporter3'
    metrics_path: '/metrics'
    honor_labels: true
    static_configs:
      - targets: ['nats-exporter3:7777']
