version: "3"
services:
  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    environment:
      - REDIS_HOSTS=redis:redis:6379:0:yourpassword
    ports:
      - "8081:8081"

  redis:
    image: redis
    command: redis-server --requirepass yourpassword
    # command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  redis-cluster:
    container_name: redis-cluster
    image: grokzen/redis-cluster
    environment:
      - IP=0.0.0.0
      - INITIAL_PORT=7001
    ports:
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
      - 7006:7006

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080

  db:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: benchmark
    ports:
     - 3306:3306
