version: '2'

services:
  etcd1:
    container_name: etcd1
    image: docker.io/bitnami/etcd:3
    ports:
      - 2380:2380
      - 2379:2379
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:22380,etcd3=http://etcd3:32380
      # - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_STATE=existing
    volumes:
      - ./data1:/bitnami/etcd/data

  etcd2:
    container_name: etcd2
    image: docker.io/bitnami/etcd:3
    ports:
      - 22380:22380
      - 22379:22379
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:22380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:22380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:22379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:22379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:22380,etcd3=http://etcd3:32380
      # - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_STATE=existing
    volumes:
      - ./data2:/bitnami/etcd/data

  etcd3:
    container_name: etcd3
    image: docker.io/bitnami/etcd:3
    ports:
      - 32380:32380
      - 32379:32379
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:32380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:32380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:32379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:32379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:22380,etcd3=http://etcd3:32380
      # - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_STATE=existing
    volumes:
      - ./data3:/bitnami/etcd/data     

  e3w:
    container_name: e3w
    image: soyking/e3w:latest
    volumes:
      - ./config.default.ini:/app/conf/config.default.ini
    ports:
      - "8080:8080"
    depends_on:
      - etcd1
      - etcd2
      - etcd3
