---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
# 
# 只有當 elasticsearch 需要輸入帳號密碼時才需要啟用以下兩個變數
# elasticsearch.username: elastic
# elasticsearch.password: changeme
