version: '3'

services:
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080

  db:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: upload_file
      MYSQL_ROOT_PASSWORD: root
    ports:
     - 3306:3306
