// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.3
// source: msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MSG_HEADER int32

const (
	MSG_HEADER_C_S_TRY_REG MSG_HEADER = 1
	MSG_HEADER_C_S_PING    MSG_HEADER = 12
	MSG_HEADER_S_C_PONG    MSG_HEADER = 1017
)

// Enum value maps for MSG_HEADER.
var (
	MSG_HEADER_name = map[int32]string{
		1:    "C_S_TRY_REG",
		12:   "C_S_PING",
		1017: "S_C_PONG",
	}
	MSG_HEADER_value = map[string]int32{
		"C_S_TRY_REG": 1,
		"C_S_PING":    12,
		"S_C_PONG":    1017,
	}
)

func (x MSG_HEADER) Enum() *MSG_HEADER {
	p := new(MSG_HEADER)
	*p = x
	return p
}

func (x MSG_HEADER) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSG_HEADER) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (MSG_HEADER) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x MSG_HEADER) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MSG_HEADER) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MSG_HEADER(num)
	return nil
}

// Deprecated: Use MSG_HEADER.Descriptor instead.
func (MSG_HEADER) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

type C_S_TryReg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account    *string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`         // 账号
	Passwd     *string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`           // 密码
	IsLogin    *bool   `protobuf:"varint,3,opt,name=isLogin" json:"isLogin,omitempty"`        // 是否登录
	Lang       *string `protobuf:"bytes,4,opt,name=lang" json:"lang,omitempty"`               // 客户端语言, chn: 简体中文, tw: 繁体中文, en: 英文, vn: 越南文, tha: 泰文
	IsTrial    *bool   `protobuf:"varint,5,opt,name=isTrial" json:"isTrial,omitempty"`        // 是否为试玩
	ClientKind *uint32 `protobuf:"fixed32,6,opt,name=clientKind" json:"clientKind,omitempty"` // 始终为CLIENT_KIND.CLIENT_WEB
	Ag         *string `protobuf:"bytes,7,opt,name=ag" json:"ag,omitempty"`                   // 代理商账号
	Sid        *string `protobuf:"bytes,8,opt,name=sid" json:"sid,omitempty"`                 // 从浏览器url中获取的sid参数
	Is3D       *bool   `protobuf:"varint,9,opt,name=is3D" json:"is3D,omitempty"`              // 是否为3D版本
	Balance    *uint32 `protobuf:"fixed32,10,opt,name=balance" json:"balance,omitempty"`      // 从token中获取的账户余额
	Sn         *string `protobuf:"bytes,11,opt,name=sn" json:"sn,omitempty"`                  // 厅主编码
	Ip         *string `protobuf:"bytes,12,opt,name=ip" json:"ip,omitempty"`                  // 客户端真实IP地址
}

func (x *C_S_TryReg) Reset() {
	*x = C_S_TryReg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_S_TryReg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_S_TryReg) ProtoMessage() {}

func (x *C_S_TryReg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_S_TryReg.ProtoReflect.Descriptor instead.
func (*C_S_TryReg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *C_S_TryReg) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *C_S_TryReg) GetPasswd() string {
	if x != nil && x.Passwd != nil {
		return *x.Passwd
	}
	return ""
}

func (x *C_S_TryReg) GetIsLogin() bool {
	if x != nil && x.IsLogin != nil {
		return *x.IsLogin
	}
	return false
}

func (x *C_S_TryReg) GetLang() string {
	if x != nil && x.Lang != nil {
		return *x.Lang
	}
	return ""
}

func (x *C_S_TryReg) GetIsTrial() bool {
	if x != nil && x.IsTrial != nil {
		return *x.IsTrial
	}
	return false
}

func (x *C_S_TryReg) GetClientKind() uint32 {
	if x != nil && x.ClientKind != nil {
		return *x.ClientKind
	}
	return 0
}

func (x *C_S_TryReg) GetAg() string {
	if x != nil && x.Ag != nil {
		return *x.Ag
	}
	return ""
}

func (x *C_S_TryReg) GetSid() string {
	if x != nil && x.Sid != nil {
		return *x.Sid
	}
	return ""
}

func (x *C_S_TryReg) GetIs3D() bool {
	if x != nil && x.Is3D != nil {
		return *x.Is3D
	}
	return false
}

func (x *C_S_TryReg) GetBalance() uint32 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *C_S_TryReg) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

func (x *C_S_TryReg) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

type C_S_Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *uint64 `protobuf:"fixed64,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (x *C_S_Ping) Reset() {
	*x = C_S_Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_S_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_S_Ping) ProtoMessage() {}

func (x *C_S_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_S_Ping.ProtoReflect.Descriptor instead.
func (*C_S_Ping) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *C_S_Ping) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type S_C_Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTime *uint64 `protobuf:"fixed64,1,opt,name=serverTime" json:"serverTime,omitempty"`
	Timestamp  *uint64 `protobuf:"fixed64,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (x *S_C_Pong) Reset() {
	*x = S_C_Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_C_Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_C_Pong) ProtoMessage() {}

func (x *S_C_Pong) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_C_Pong.ProtoReflect.Descriptor instead.
func (*S_C_Pong) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *S_C_Pong) GetServerTime() uint64 {
	if x != nil && x.ServerTime != nil {
		return *x.ServerTime
	}
	return 0
}

func (x *S_C_Pong) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

var File_msg_proto protoreflect.FileDescriptor

var file_msg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69,
	0x6e, 0x22, 0x96, 0x02, 0x0a, 0x0a, 0x43, 0x5f, 0x53, 0x5f, 0x54, 0x72, 0x79, 0x52, 0x65, 0x67,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x61, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x54, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x54, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0a,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x67,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x73, 0x33, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x33, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x07, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x73, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x28, 0x0a, 0x08, 0x43, 0x5f,
	0x53, 0x5f, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x22, 0x48, 0x0a, 0x08, 0x53, 0x5f, 0x43, 0x5f, 0x50, 0x6f, 0x6e, 0x67,
	0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2a, 0x3a,
	0x0a, 0x0a, 0x4d, 0x53, 0x47, 0x5f, 0x48, 0x45, 0x41, 0x44, 0x45, 0x52, 0x12, 0x0f, 0x0a, 0x0b,
	0x43, 0x5f, 0x53, 0x5f, 0x54, 0x52, 0x59, 0x5f, 0x52, 0x45, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x43, 0x5f, 0x53, 0x5f, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x0c, 0x12, 0x0d, 0x0a, 0x08, 0x53,
	0x5f, 0x43, 0x5f, 0x50, 0x4f, 0x4e, 0x47, 0x10, 0xf9, 0x07, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x6d, 0x73, 0x67,
}

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData = file_msg_proto_rawDesc
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_proto_rawDescData)
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_msg_proto_goTypes = []interface{}{
	(MSG_HEADER)(0),    // 0: main.MSG_HEADER
	(*C_S_TryReg)(nil), // 1: main.C_S_TryReg
	(*C_S_Ping)(nil),   // 2: main.C_S_Ping
	(*S_C_Pong)(nil),   // 3: main.S_C_Pong
}
var file_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_S_TryReg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_S_Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_C_Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_rawDesc = nil
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
