version: '3'

services:
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: jim
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
    ports:
     - 3306:3306

  db1:
    container_name: db1
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: message
      MYSQL_USER: jim
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
    ports:
     - 3301:3306

  db2:
    container_name: db2
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: message
      MYSQL_USER: jim
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
    ports:
     - 3302:3306

  db3:
    container_name: db3
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: message
      MYSQL_USER: jim
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
    ports:
     - 3303:3306

