version: "3"
services:
  console:
    container_name: console
    # no user/password support ...
    # https://github.com/piotrpersona/nats-streaming-ui
    image: piotrpersona/nats-streaming-ui:latest
    environment:
      - STAN_URL=http://nats1:4221
      - STAN_MONITOR_URL=http://nats1:8221
      - STAN_CLUSTER=stan
    ports:
      - 8282:8282 

  nats1:
    container_name: stan1
    image: nats-streaming
    command: ["-c","cluster.config"]
    restart: always
    ports:
      - 4221:4221
      - 6221:6221
      - 8221:8221 # http 監控 port
    volumes:
     - "../fullenv/cluster1.config:/cluster.config"

  nats2:
    container_name: stan2
    image: nats-streaming
    command: ["-c","cluster.config"]
    restart: always
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222 # http 監控 port
    volumes:
     - "../fullenv/cluster2.config:/cluster.config"

  nats3:
    container_name: stan3
    image: nats-streaming
    command: ["-c","cluster.config"]
    restart: always
    ports:
      - 4223:4223
      - 6223:6223
      - 8223:8223 # http 監控 port
    volumes:
     - "../fullenv/cluster3.config:/cluster.config"

