version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_BROKER_ID: "1"
      KAFKA_LOG_DIRS: "/opt/kafka/data"
      KAFKA_CREATE_TOPICS: "sarama:1:2"

  kafdrop:
    container_name: kafdrop
    image: thomsch98/kafdrop
    ports:
      - "9010:9010"
    environment:
      ZK_HOSTS: zookeeper:2181
      LISTEN: 9010