version: '3.1'

services:
  mongo1:
    image: mongo
    container_name: mongo1
    command: mongod --replSet my-mongo-set
    ports:
      - 3001:27017
    networks:
      - proxy-network

  mongo2:
    image: mongo
    container_name: mongo2
    command: mongod --replSet my-mongo-set
    ports:
      - 3002:27017
    networks:
      - proxy-network

  mongo3:
    image: mongo
    container_name: mongo3
    command: mongod --replSet my-mongo-set
    ports:
      - 3003:27017
    networks:
      - proxy-network


networks:
  proxy-network:
    driver: bridge