version: '3.5'
services:

  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.2.1'
    ports:
      - '9200:9200'
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # ELASTIC_PASSWORD: changeme
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  kibana:
    container_name: "kibana"
    image: 'docker.elastic.co/kibana/kibana:7.2.1'
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch

  apm-server:
    container_name: "apm-server"
    image: 'docker.elastic.co/apm/apm-server:7.2.1'
    ports:
      - "8200:8200"
    volumes:
      - ./config/apm-server.yml:/usr/share/apm-server/config/apm-server.yml:ro
    depends_on:
      - elasticsearch
