version: "3"
services:
  arangodb:
    container_name: arangodb
    image: arangodb/arangodb:3.6.2
    environment:
      # - ARANGO_NO_AUTH=1 # open it to disable authorization check
      - ARANGO_ROOT_PASSWORD=somepassword
    ports:
      - "8529:8529"
    networks:
      - proxy-network


networks:
  proxy-network:
    driver: bridge


