@startuml

title ReadMessage

skinparam ParticipantPadding 80
skinparam BoxPadding 10

participant "ClientRequest" as UsrMsg #APPLICATION

box "DBManager" #C7D7D8
participant "CreateMessage" as DBWriter #BUSINESS
participant "DbLocDecide" as DBBroker #BUSINESS
end box

box "MySQL-main/nodes" #C7D7D8
participant "MySQL(s)" as Dbs #BUSINESS
end box

autonumber "0."

UsrMsg -> DBWriter : [Request]\n messages within GroupID
activate UsrMsg #F5DDAD

activate DBWriter #F5DDAD
DBWriter <--> DBBroker : [loc]\nAsk for group table location

note right of DBBroker
1. Query MainDb for loc,
if local cache missd.
2. if groups loc was not found in table,
return the less group db loc.
end note

activate DBBroker #LightBlue
DBBroker <--> Dbs : [db:GroupInDB]\nRetrieve Groups Loc
deactivate DBBroker

DBWriter <--> Dbs : [Insert]\nInsert Message into NodeDbs[loc]

DBWriter -> UsrMsg : [Response]\nResult
deactivate DBWriter

deactivate UsrMsg

@enduml