@startuml

title ReadMessage

skinparam ParticipantPadding 80
skinparam BoxPadding 10

participant "ClientRequest" as UsrMsg #APPLICATION

box "DBManager" #C7D7D8
participant "ReadMessage" as DBReader #BUSINESS
participant "DbLocDecide" as DBBroker #BUSINESS
end box

box "MySQL-main/nodes" #C7D7D8
participant "MySQL(s)" as Dbs #BUSINESS
end box

autonumber "0."

UsrMsg -> DBReader : [Request]\n messages within GroupID
activate UsrMsg #F5DDAD

activate DBReader #F5DDAD
DBReader <--> DBBroker : [loc]\nAsk for group table location


activate DBBroker #F5DDAD
DBBroker <--> Dbs : [db:GroupInDB]\nRetrieve Groups Loc
note right of DBBroker
if `loc` is not found, return error
end note
deactivate DBBroker

DBReader <--> Dbs : [Read]\nRead Message from NodeDbs[loc]

DBReader -> UsrMsg : [Response]\nResult
deactivate DBReader

deactivate UsrMsg

@enduml