version: "3"
services:
  redis-cluster:
    container_name: redis-cluster
    image: grokzen/redis-cluster
    environment:
      - IP=0.0.0.0
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
