version: '3.1'

services:
  minio:
    image: minio/minio
    container_name: minio
    command: ["server","/data","--console-address",":9001"]
    environment:
      MINIO_ROOT_USER: jim
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 9001:9001

