version: '3'

services:
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    environment:
      API_URL: swagger/api.yml
    volumes:
      - ./swagger.yml:/usr/share/nginx/html/swagger/api.yml
      - ./demo.png:/usr/share/nginx/html/img/demo.png
    ports:
      - 8888:8080

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080

  redis-ui:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    environment:
      - REDIS_HOSTS=redis:redis:6379:0:yourpassword
    ports:
      - "8081:8081"

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
     - 3306:3306

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass yourpassword
    # command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
