version: '3'

services:
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

